services:
  - type: web
    name: achzodyt-bilans-coaching
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MAIL_USER
        sync: false
      - key: MAIL_PASS
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: COACH_EMAIL
        sync: false
      - key: COACH_PASSWORD
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
